### ISSUE TITLE
Getting an error module 'runhouse' has no attribute 'exists'

### ISSUE THREAD

**Issue by kilimchoi** [run-house/tutorials#3]
Hi I just installed runhouse from cli and I'm getting `module 'runhouse' has no attribute 'exists'` when I run [p01_sd_generate.py](https://github.com/run-house/tutorials/blob/main/t01_Stable_Diffusion/p01_sd_generate.py)

Is the library up to date?

**Comment by dongreenberg** [comment]
@kilimchoi, did this get resolved?
